/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JT */

#ifndef _Included_JT
#define _Included_JT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JT
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JT_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
